# home-bgp.yaml  (advertise every LB IP and each node’s PodCIDR)
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: home-peering
spec:
  nodeSelector:                 # ← label your nodes or leave {} for all
    matchLabels:
      bgp: "enable"
  virtualRouters:
  - localASN: 65000
    exportPodCIDR: true         # keep advertising the node CIDR
    serviceSelector: {}         # {} = match every Service → advertise LB IPs
    neighbors:
    - peerAddress: "192.168.1.1/32"
      peerASN: 64512

